# Generated by Django 4.0.7 on 2023-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribePage',
        ),
    ]
