# Generated by Django 4.0.6 on 2022-08-20 04:47

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='author',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(default=2022, max_length=250),
            preserve_default=False,
        ),
    ]
