# Generated by Django 4.0.6 on 2022-08-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexpage_author_blogpage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='author',
        ),
    ]
