# Generated by Django 4.0.6 on 2022-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_eventpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='location',
        ),
    ]
