# Generated by Django 4.0.6 on 2022-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_eventpage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='image_check',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
