# Generated by Django 4.0.6 on 2022-08-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_eventpage_image_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='generate_cover',
            field=models.BooleanField(default=False),
        ),
    ]
