# Generated by Django 4.0.6 on 2022-08-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpage_cover_image_blogpage_generate_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
