# Generated by Django 4.0.7 on 2022-09-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_engineer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
