# Generated by Django 4.0.7 on 2023-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='notify_subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
