# Generated by Django 4.0.6 on 2022-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
