# Generated by Django 4.0.6 on 2022-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'index page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
