# Generated by Django 4.0.6 on 2022-08-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homeitem_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeitem',
            options={'verbose_name': 'Homepage Item', 'verbose_name_plural': 'Homepage Items'},
        ),
    ]
