# Generated by Django 4.0.6 on 2022-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homeitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeitem',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
