# Generated by Django 4.0.7 on 2023-07-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='notify_subscribers',
            field=models.BooleanField(default=False),
        ),
    ]
