# Generated by Django 4.0.7 on 2022-09-19 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0016_alter_codeblockpage_content_alter_engineer_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeBlockPage',
        ),
    ]
