# Generated by Django 4.0.7 on 2023-06-29 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('feed', '0004_bookdocument_bookpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='BookDocument',
        ),
    ]
