# Generated by Django 4.0.7 on 2023-06-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0002_auto_20230612_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
