# Generated by Django 4.0.7 on 2023-06-25 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0003_alter_userprofile_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recurrence', models.CharField(max_length=100)),
                ('recurrence_interval', models.IntegerField()),
                ('recurrence_count', models.IntegerField()),
                ('recurrence_by_day', models.CharField(max_length=100)),
                ('options', models.CharField(default='["Apple", "Google", "iCal", "Outlook.com", "Microsoft 365", "Microsoft Teams"]', max_length=200)),
                ('time_zone', models.CharField(default='currentBrowser', max_length=50)),
                ('location', models.CharField(default='Fantasy Marketplace', max_length=100)),
                ('button_style', models.CharField(default='date', max_length=50)),
                ('size', models.IntegerField(default=15)),
                ('light_mode', models.CharField(default='bodyScheme', max_length=50)),
                ('description', models.TextField(default='[p][strong]快来EAC和朋友们一起聊聊天把[/strong] 你订阅的朋友 [u]已经[/u] 上线! 🚀[/p][p]💻 [em]点击链接来访问:[/em][br]&rarr; [url]https://eac.aaron404.com/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echo_atrium.userprofile')),
            ],
        ),
    ]
