# Generated by Django 4.0.7 on 2023-06-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='options',
        ),
    ]
