# Generated by Django 4.0.7 on 2023-06-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0005_remove_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='button_style',
            new_name='buttonStyle',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='light_mode',
            new_name='lightMode',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='recurrence_by_day',
            new_name='recurrenceByDay',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_zone',
            new_name='timeZone',
        ),
    ]
