# Generated by Django 4.0.7 on 2023-06-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0006_rename_button_style_event_buttonstyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
