# Generated by Django 4.0.7 on 2023-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_atrium', '0007_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
